// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");

import { PrivateVaultContract, VaultPrivateState } from '../contracts/managed/private-vault/index.js';
import { witnesses } from './witnesses.js';
import { createVaultPrivateState } from './witnesses.js';

export interface VaultAPIConfig {
  contractAddress?: string;
  privateStatePath?: string;
}

export class VaultAPI {
  private contract: PrivateVaultContract;
  private privateState: VaultPrivateState;

  constructor(config?: VaultAPIConfig) {
    this.contract = new PrivateVaultContract();
    this.privateState = createVaultPrivateState(
      config?.contractAddress || '',
      new Uint8Array(32)
    );
  }

  // Initialize vault with first deposit
  async initVault(coinInfo: unknown): Promise<string> {
    try {
      const result = await this.contract.initVault(coinInfo, this.privateState);
      return `Vault initialized successfully: ${JSON.stringify(result)}`;
    } catch (error) {
      throw new Error(`Failed to initialize vault: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  // Deposit tokens into existing vault
  async deposit(coinInfo: unknown): Promise<string> {
    try {
      const result = await this.contract.deposit(coinInfo, this.privateState);
      return `Deposit successful: ${JSON.stringify(result)}`;
    } catch (error) {
      throw new Error(`Failed to deposit: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  // Withdraw tokens from vault
  async withdraw(recipient: string, amount: bigint): Promise<string> {
    try {
      const result = await this.contract.withdraw(
        null, // proof generated by circuit
        recipient,
        amount,
        this.privateState
      );
      return `Withdrawal successful: ${JSON.stringify(result)}`;
    } catch (error) {
      throw new Error(`Failed to withdraw: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  // Get vault state (public data)
  async getVaultState(): Promise<[boolean, bigint, bigint]> {
    try {
      return await this.contract.getVaultState(this.privateState);
    } catch (error) {
      throw new Error(`Failed to get vault state: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
}

// Helper function to create API instance
export async function createVaultAPI(config?: VaultAPIConfig): Promise<VaultAPI> {
  return new VaultAPI(config);
}
