// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { PrivateState, WitnessContext } from '@midnight-ntwrk/compact-runtime';

// Private state type for the vault dApp
export interface VaultPrivateState extends PrivateState {
  readonly vaultOwner: string;
  readonly secretKey: Uint8Array;
}

// Witness for initializing vault
export const initVault = {
  initialize: async (
    context: WitnessContext<{ hasShieldedTokens: boolean }, VaultPrivateState>
  ) => {
    const { secretKey, vaultOwner } = context.privateState;
    if (!secretKey || !vaultOwner) {
      throw new Error('Missing required private state: secretKey or vaultOwner');
    }
    return {
      circuitInput: vaultOwner,
      privateState: context.privateState,
    };
  },
};

// Witness for deposit circuit
export const deposit = {
  depositTokens: async (
    context: WitnessContext<{ hasShieldedTokens: boolean; totalShieldedDeposits: bigint }, VaultPrivateState>,
    coinInfo: unknown
  ) => {
    if (!context.privateState.secretKey) {
      throw new Error('Secret key not found in private state');
    }
    return {
      circuitInput: coinInfo,
      privateState: context.privateState,
    };
  },
};

// Witness for withdraw circuit - generates nullifier and proof
export const withdraw = {
  prepareWithdraw: async (
    context: WitnessContext<
      { hasShieldedTokens: boolean; totalWithdrawals: bigint; nullifiers: Map<string, boolean> },
      VaultPrivateState
    >,
    recipient: string,
    amount: bigint
  ) => {
    const { secretKey, vaultOwner } = context.privateState;

    if (!secretKey) {
      throw new Error('Secret key not found in private state');
    }

    // Generate a unique nullifier for this withdrawal
    const nullifier = await crypto.subtle.digest(
      'SHA-256',
      new TextEncoder().encode(`${vaultOwner}-${Date.now()}-${amount}`)
    );

    const nullifierHex = Array.from(new Uint8Array(nullifier))
      .map(b => b.toString(16).padStart(2, '0'))
      .join('');

    return {
      circuitInput: {
        proof: null, // Proof is generated by the ZK circuit
        nullifier: nullifierHex,
        recipient,
        withdraw_amount: amount,
      },
      privateState: context.privateState,
    };
  },
};

// Helper to create initial private state
export function createVaultPrivateState(
  vaultOwner: string,
  secretKey: Uint8Array
): VaultPrivateState {
  return {
    vaultOwner,
    secretKey,
  };
}

// Export all witnesses
export const witnesses = {
  initVault,
  deposit,
  withdraw,
};
