// Mock PrivateVaultContract for development/testing
// This would be generated by `compact compile`

export class PrivateVaultContract {
  async initVault(_coinInfo, _privateState) {
    return 'Vault initialized (mock)';
  }

  async deposit(_coinInfo, _privateState) {
    return 'Deposit successful (mock)';
  }

  async withdraw(_proof, _recipient, _amount, _privateState) {
    return 'Withdrawal successful (mock)';
  }

  async getVaultState(_privateState) {
    return [true, BigInt(0), BigInt(0)];
  }
}

export default PrivateVaultContract;
